Whatevs

diff --git a/common b/common
--- a/common
+++ b/common
@@ -3,11 +3,74 @@
 set -e
 set -o pipefail
 
-GIT_REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
-GIT_BRANCH="$(cd "${GIT_REPO}" && git symbolic-ref --short HEAD 2> /dev/null || echo -n '')"
-
 DOCKER_REPO='574271486042.dkr.ecr.us-east-1.amazonaws.com'
-DOCKER_IMAGE="$(basename "$(cd "$(dirname "${BASH_SOURCE[1]}")" && pwd)")"
-DOCKER_TAG="${GIT_BRANCH:-development}"
-IMAGE_NAME="${DOCKER_IMAGE}:${DOCKER_TAG}"
 AWS_IMAGE_NAME="${DOCKER_REPO}/${IMAGE_NAME}"
+
+getAwsImageName()
+{
+  set -e
+  set -o pipefail
+
+  local DIRECTORY="${1}"
+  if [[ -z "${DIRECTORY}" ]]; then
+    echo 'DIRECTORY is required.' 1>&2
+    exit 1
+  fi
+
+  echo "${DOCKER_REPO}/$(getTaggedDockerImageName "${DIRECTORY}")"
+}
+
+getDockerImageName()
+{
+  set -e
+  set -o pipefail
+
+  local DIRECTORY="${1}"
+  if [[ -z "${DIRECTORY}" ]]; then
+    echo 'DIRECTORY is required.' 1>&2
+    exit 1
+  fi
+
+  basename "$(cd "${DIRECTORY}" && pwd)"
+}
+
+getDockerTag()
+{
+  set -e
+  set -o pipefail
+
+  getGitBranch
+}
+
+getGitBranch()
+{
+  set -e
+  set -o pipefail
+
+  cd "$(getGitRepo)"
+  git symbolic-ref --short HEAD
+}
+
+getGitRepo()
+{
+  set -e
+  set -o pipefail
+
+  cd "$(dirname "${BASH_SOURCE[0]}")"
+  git rev-parse --show-toplevel
+}
+
+getTaggedDockerImageName()
+{
+  set -e
+  set -o pipefail
+
+  local DIRECTORY="${1}"
+  if [[ -z "${DIRECTORY}" ]]; then
+    echo 'DIRECTORY is required.' 1>&2
+    exit 1
+  fi
+
+  echo "$(getDockerImageName "${DIRECTORY}"):$(getDockerTag)"
+}
+
