Mooore.

diff --git a/images/common b/images/common
--- a/images/common
+++ b/images/common
@@ -3,31 +3,86 @@
 set -e
 set -o pipefail
 
+DEBUG=$(true)
 DNS_DOMAIN='lepertheory.net'
 DOCKER_REPO='574271486042.dkr.ecr.us-east-1.amazonaws.com'
 IMAGES_BASE='images'
 DOCKER_ROOT_HOME="${HOME}/.docker-home"
+BASE_DOCKER_NAME='base'
+CONTROLLER_DOCKER_NAME='controller'
 
-#buildDockerImage()
-#{
-#  set -e
-#  set -o pipefail
-#
-#  local DIRECTORY="${1}"
-#  if [[ -z "${DIRECTORY}" ]]; then
-#    echo 'DIRECTORY is required.' 1>&2
-#    exit 1
-#  fi
-#
-#  local BASE_IMAGE="$(getBaseImage "${DIRECTORY}")"
-#  local BASE_DOCKERFILE="$(getDockerfile "${BASE_IMAGE}" || echo -n)"
-#  if [[ -f "${BASE_DOCKERFILE}" ]]; then
-#    buildDockerImage "$(dirname "${BASE_DOCKERFILE}")"
-#  fi
-#
-#  local build_command=( {
-#  
-#}
+buildDockerImage()
+{
+  set -e
+  set -o pipefail
+
+  local DIRECTORY="${1}"
+  if [[ -z "${DIRECTORY}" ]]; then
+    echo 'DIRECTORY is required.' 1>&2
+    exit 1
+  fi
+  shift
+
+  local BASE_IMAGE="$(getBaseImage "${DIRECTORY}")"
+  local BASE_DOCKERFILE="$(getDockerfile "${BASE_IMAGE}" || echo -n)"
+  if [[ -f "${BASE_DOCKERFILE}" ]]; then
+    buildDockerImage "$(dirname "${BASE_DOCKERFILE}")"
+  fi
+
+  local build_command=(docker build)
+  local build_command+=(--build-arg GIT_BRANCH="$(getGitBranch)")
+  local build_command+=(--tag "$(getTaggedDockerImageName "${DIRECTORY}")")
+  local build_command+=(--label REPO_SOURCE="$(getGitRepoPath "${DIRECTORY}")")
+  if [[ -f "${BASE_DOCKERFILE}" ]]; then
+    build_command+=(--label BASE_DOCKERFILE="$(getGitRepoPath "${BASE_DOCKERFILE}")")
+  fi
+  while [[ "${1}" == '--dockerArg' ]]; do
+    shift
+    build_command+=("${1}")
+    shift
+  done
+  build_command+=("${DIRECTORY}")
+  
+  if [[ ${DEBUG} ]]; then
+    echo "build_command: ${build_command[@]}"
+  fi
+  "${build_command[@]}"
+}
+
+ensureContainerIsRunningInBackground()
+{
+  set -e
+  set -o pipefail
+
+  local TAGGED_IMAGE_NAME="${1}"
+  if [[ -z "${TAGGED_IMAGE_NAME}" ]]; then
+    echo 'TAGGED_IMAGE_NAME is required.' 1>&2
+    exit 1
+  fi
+
+  ensureImageExists
+}
+
+ensureImageExists()
+{
+  set -e
+  set -o pipefail
+
+  local IMAGE_NAME_AND_TAG="${1}"
+  if [[ -z "${IMAGE_NAME_AND_TAG}" ]]; then
+    echo 'IMAGE_NAME_AND_TAG is required.' 1>&2
+    exit 1
+  fi
+
+  local IMAGE_NAME="${IMAGE_NAME_AND_TAG%%:*}"
+  local IMAGE_TAG="${IMAGE_NAME_AND_TAG#*:}"
+  if [[ "${IMAGE_TAG}" != "$(getGitBranch)" ]]; then
+    echo 'Unhandled. Deal.' 1>&2
+    exit 2
+  fi
+
+  
+}
 
 getAwsImageName()
 {
@@ -74,6 +129,22 @@ getDockerfile()
   else
     return 1
   fi
+}
+
+getDockerContainerInfoByName()
+{
+  set -e
+  set -o pipefail
+
+  local CONTAINER_NAME="${1}"
+  if [[ -z "${CONTAINER_NAME}" ]]; then
+    echo 'CONTAINER_NAME is required.' 1>&2
+    exit 1
+  fi
+
+  NAME_ID_IMAGE=($(docker ps --no-trunc --format '{{.Names}} {{.ID}} {{.Image}}' | \
+                   grep -E '^'"${CONTAINER_NAME}"'\s+'))
+  echo "${NAME_ID_IMAGE[@]}"
 }
 
 getDockerImageName()
@@ -205,6 +276,21 @@ getTaggedDockerImageName()
   fi
 
   echo "$(getDockerImageName "${DIRECTORY}"):$(getDockerTag)"
+}
+
+isDockerContainerNameRunning()
+{
+  set -e
+  set -o pipefail
+
+  local CONTAINER_NAME="${1}"
+  if [[ -z "${CONTAINER_NAME}" ]]; then
+    echo 'CONTAINER_NAME is required.' 1>&2
+    exit 1
+  fi
+
+  local CONTAINER_INFO=($(getDockerContainerInfoByName "${CONTAINER_NAME}"))
+  return $(( ${#CONTAINER_INFO[@]} != 3 ))
 }
 
 if [[ "${0}" == "${BASH_SOURCE[0]}" ]]; then
