yolo

diff --git a/images/common b/images/common
--- a/images/common
+++ b/images/common
@@ -6,6 +6,28 @@ set -o pipefail
 DNS_DOMAIN='lepertheory.net'
 DOCKER_REPO='574271486042.dkr.ecr.us-east-1.amazonaws.com'
 IMAGES_BASE='images'
+DOCKER_ROOT_HOME="${HOME}/.docker-home"
+
+#buildDockerImage()
+#{
+#  set -e
+#  set -o pipefail
+#
+#  local DIRECTORY="${1}"
+#  if [[ -z "${DIRECTORY}" ]]; then
+#    echo 'DIRECTORY is required.' 1>&2
+#    exit 1
+#  fi
+#
+#  local BASE_IMAGE="$(getBaseImage "${DIRECTORY}")"
+#  local BASE_DOCKERFILE="$(getDockerfile "${BASE_IMAGE}" || echo -n)"
+#  if [[ -f "${BASE_DOCKERFILE}" ]]; then
+#    buildDockerImage "$(dirname "${BASE_DOCKERFILE}")"
+#  fi
+#
+#  local build_command=( {
+#  
+#}
 
 getAwsImageName()
 {
